title: azurezhc.github.io
description: AzureZHC的程序随笔
theme: jekyll-theme-cayman
email: azurezhc@gamil.com


markdown: kramdown

kramdown:
  math_engine: mathjax
  input: kramdown

relative_links:
  enabled: true
  collections: false