baseURL = "http://azurezhc.github.io/"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

# 网站标题
title = "azurezhc的游戏开发人生"

# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true

# 作者配置
[author]
  name = "azurezhc"
  email = "azurezhc@gmail.com"
  link = ""

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/文章目录"
    # title will be shown when you hover on this menu link
    # 当您将鼠标悬停在此菜单链接上时, 将显示标题
    title = ""


[params]
  title = "azurezhc的游戏开发人生"
  description = "azurezhc记录其游戏开发人生的博客"

  [params.header]
    [params.header.title]
      name = "主页"

  [params.home]
    [params.home.profile]
      title = "游戏开发博客"
      subtitle = "这里是azurezhc记录其游戏开发人生的博客"
      typeit = false

  [params.page]
    [params.page.math] 
      enable = true

[module]
  [[module.imports]]
    path = "link-handling-mod-hugo-dfd"